; Copyright © Microsoft Corp. 1995-2001

[Theme]

; My Computer
[CLSID\{20D04FE0-3AEA-1069-A2D8-08002B30309D}\DefaultIcon]
DefaultValue=C:\WINDOWS\Resources\Themes\MS PLUS Space\Space My Computer.ico,0

; My Documents
[CLSID\{450D8FBA-AD25-11D0-98A8-0800361B1103}\DefaultIcon]
DefaultValue=C:\WINDOWS\SYSTEM32\mydocs.dll,0

; My Network Places
[CLSID\{208D2C60-3AEA-1069-A2D7-08002B30309D}\DefaultIcon]
DefaultValue=C:\WINDOWS\Resources\Themes\MS PLUS Space\Space Network Neighborhood.ico,0

; Recycle Bin
[CLSID\{645FF040-5081-101B-9F08-00AA002F954E}\DefaultIcon]
full=C:\WINDOWS\Resources\Themes\MS PLUS Space\Space Recycle Full.ico,0
empty=C:\WINDOWS\Resources\Themes\MS PLUS Space\Space Recycle Empty.ico,0



[Control Panel\Colors]
ActiveTitle=0 0 0
Background=0 0 0
Hilight=0 0 0
HilightText=0 255 0
TitleText=0 255 0
Window=255 255 255
WindowText=0 0 0
Scrollbar=192 200 208
InactiveTitle=80 96 104
Menu=128 144 152
WindowFrame=0 0 0
MenuText=0 0 0
ActiveBorder=128 144 152
InactiveBorder=128 144 152
AppWorkspace=83 96 102
ButtonFace=128 144 152
ButtonShadow=80 96 104
GrayText=80 96 104
ButtonText=0 0 0
InactiveTitleText=192 192 192
ButtonHilight=192 200 208
ButtonDkShadow=0 0 0
ButtonLight=128 144 152
InfoText=0 0 0
InfoWindow=255 255 255
GradientActiveTitle=0 0 0
GradientInactiveTitle=80 96 104
ButtonAlternateFace=181 181 181
HotTrackingColor=0 0 128
MenuHilight=49 106 197
MenuBar=236 233 216


[Control Panel\Cursors]
Arrow=%WinDir%Resources\Themes\MS PLUS Space\Space Normal Select.cur
Help=%WinDir%Resources\Themes\MS PLUS Space\Space Help Select.cur
AppStarting=%WinDir%Resources\Themes\MS PLUS Space\Space Working in Background.ani
Wait=%WinDir%Resources\Themes\MS PLUS Space\Space Busy.ani
NWPen=%WinDir%Resources\Themes\MS PLUS Space\Space Handwriting.cur
No=%WinDir%Resources\Themes\MS PLUS Space\Space Unavailable.cur
SizeNS=%WinDir%Resources\Themes\MS PLUS Space\Space Vertical Resize.cur
SizeWE=%WinDir%Resources\Themes\MS PLUS Space\Space Horizontal Resize.cur
Crosshair=%WinDir%Resources\Themes\MS PLUS Space\Space Precision Select.cur
IBeam=%WinDir%Resources\Themes\MS PLUS Space\Space Text Select.cur
SizeNWSE=%WinDir%Resources\Themes\MS PLUS Space\Space Diagonal Resize 1.cur
SizeNESW=%WinDir%Resources\Themes\MS PLUS Space\Space Diagonal Resize 2.cur
SizeAll=%WinDir%Resources\Themes\MS PLUS Space\Space Move.cur
UpArrow=%WinDir%Resources\Themes\MS PLUS Space\Space Alternate Select.cur
DefaultValue=Windows default
DefaultValue.MUI=@themeui.dll,-2043
Link=

[Control Panel\Desktop]
Wallpaper=%WinDir%Resources\Themes\MS PLUS Space\Space wallpaper.jpg
TileWallpaper=0
WallpaperStyle=2
Pattern=
ScreenSaveActive=0

[Control Panel\Desktop\WindowMetrics]

[Metrics]
IconMetrics=76 0 0 0 75 0 0 0 75 0 0 0 1 0 0 0 248 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 144 1 0 0 0 0 0 1 0 0 0 0 77 83 32 83 97 110 115 32 83 101 114 105 102 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  
NonclientMetrics=84 1 0 0 1 0 0 0 13 0 0 0 13 0 0 0 18 0 0 0 18 0 0 0 243 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 144 1 0 0 0 0 0 1 0 0 0 0 65 98 97 100 105 32 77 84 32 67 111 110 100 101 110 115 101 100 32 76 105 103 104 116 0 0 0 0 0 0 0 0 15 0 0 0 15 0 0 0 247 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 144 1 0 0 0 0 0 1 0 0 0 0 77 83 32 83 97 110 115 32 83 101 114 105 102 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 18 0 0 0 18 0 0 0 245 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 144 1 0 0 0 0 0 1 0 0 0 0 79 67 82 32 65 32 69 120 116 101 110 100 101 100 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 245 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 144 1 0 0 0 0 0 1 0 0 0 0 77 83 32 83 97 110 115 32 83 101 114 105 102 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 245 255 255 255 0 0 0 0 0 0 0 0 0 0 0 0 144 1 0 0 0 0 0 1 0 0 0 0 79 67 82 32 65 32 69 120 116 101 110 100 101 100 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0  

[boot]
SCRNSAVE.EXE=%WinDir%system32\Space.scr


[MasterThemeSelector]
MTSM=DABJDKT
ThemeColorBPP=4


[AppEvents\Schemes\Apps\.Default\.Default\.Current]
DefaultValue=%WinDir%Resources\Themes\MS PLUS Space\Space default sound.wav
[AppEvents\Schemes\Apps\.Default\AppGPFault\.Current]
DefaultValue=%WinDir%Resources\Themes\MS PLUS Space\Space program error.wav
[AppEvents\Schemes\Apps\.Default\Close\.Current]
DefaultValue=%WinDir%Resources\Themes\MS PLUS Space\Space close program.wav
[AppEvents\Schemes\Apps\.Default\DeviceConnect\.Current]
DefaultValue=%WinDir%media\Windows XP Hardware Insert.wav
[AppEvents\Schemes\Apps\.Default\DeviceDisconnect\.Current]
DefaultValue=%WinDir%media\Windows XP Hardware Remove.wav
[AppEvents\Schemes\Apps\.Default\DeviceFail\.Current]
DefaultValue=%WinDir%media\Windows XP Hardware Fail.wav
[AppEvents\Schemes\Apps\.Default\LowBatteryAlarm\.Current]
DefaultValue=%WinDir%media\Windows XP Battery Low.wav
[AppEvents\Schemes\Apps\.Default\MailBeep\.Current]
DefaultValue=%WinDir%media\Windows XP Notify.wav
[AppEvents\Schemes\Apps\.Default\Maximize\.Current]
DefaultValue=%WinDir%Resources\Themes\MS PLUS Space\Space maximize.wav
[AppEvents\Schemes\Apps\.Default\MenuCommand\.Current]
DefaultValue=%WinDir%Resources\Themes\MS PLUS Space\Space menu command.wav
[AppEvents\Schemes\Apps\.Default\MenuPopup\.Current]
DefaultValue=%WinDir%Resources\Themes\MS PLUS Space\Space menu popup.wav
[AppEvents\Schemes\Apps\.Default\Minimize\.Current]
DefaultValue=%WinDir%Resources\Themes\MS PLUS Space\Space minimize.wav
[AppEvents\Schemes\Apps\.Default\Open\.Current]
DefaultValue=%WinDir%Resources\Themes\MS PLUS Space\Space open program.wav
[AppEvents\Schemes\Apps\.Default\PrintComplete\.Current]
DefaultValue=
[AppEvents\Schemes\Apps\.Default\RestoreDown\.Current]
DefaultValue=%WinDir%Resources\Themes\MS PLUS Space\Space restore down.wav
[AppEvents\Schemes\Apps\.Default\RestoreUp\.Current]
DefaultValue=%WinDir%Resources\Themes\MS PLUS Space\Space restore up.wav
[AppEvents\Schemes\Apps\.Default\RingIn\.Current]
DefaultValue=
[AppEvents\Schemes\Apps\.Default\Ringout\.Current]
DefaultValue=
[AppEvents\Schemes\Apps\.Default\SystemAsterisk\.Current]
DefaultValue=%WinDir%Resources\Themes\MS PLUS Space\Space asterisk.wav
[AppEvents\Schemes\Apps\.Default\SystemExclamation\.Current]
DefaultValue=%WinDir%Resources\Themes\MS PLUS Space\Space exclamation.wav
[AppEvents\Schemes\Apps\.Default\SystemExit\.Current]
DefaultValue=%WinDir%Resources\Themes\MS PLUS Space\Space exit windows.wav
[AppEvents\Schemes\Apps\.Default\SystemHand\.Current]
DefaultValue=%WinDir%Resources\Themes\MS PLUS Space\Space critical stop.wav
[AppEvents\Schemes\Apps\.Default\SystemNotification\.Current]
DefaultValue=%WinDir%media\Windows XP Balloon.wav
[AppEvents\Schemes\Apps\.Default\SystemQuestion\.Current]
DefaultValue=%WinDir%Resources\Themes\MS PLUS Space\Space question.wav
[AppEvents\Schemes\Apps\.Default\SystemStart\.Current]
DefaultValue=%WinDir%Resources\Themes\MS PLUS Space\Space startup.wav
[AppEvents\Schemes\Apps\.Default\SystemStartMenu\.Current]
DefaultValue=
[AppEvents\Schemes\Apps\.Default\WindowsLogoff\.Current]
DefaultValue=%WinDir%media\Windows XP Logoff Sound.wav
[AppEvents\Schemes\Apps\.Default\WindowsLogon\.Current]
DefaultValue=%WinDir%media\Windows XP Logon Sound.wav
[AppEvents\Schemes\Apps\Explorer\EmptyRecycleBin\.Current]
DefaultValue=%WinDir%Resources\Themes\MS PLUS Space\Space empty recycle bin.wav
[AppEvents\Schemes\Apps\Explorer\Navigating\.Current]
DefaultValue=%WinDir%media\Windows Navigation Start.wav
